# Generated by Django 5.2 on 2025-05-18 09:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format: +375 (29) 123-45-67', regex='^\\+375 \\(?(25|29|33|44)\\)? \\d{3}-\\d{2}-\\d{2}$')]),
        ),
    ]
