# Generated by Django 5.2 on 2025-05-17 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_aboutcompany'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutCompany',
        ),
    ]
