# Generated by Django 5.2 on 2025-05-17 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutcompany',
            options={'ordering': ['year'], 'verbose_name_plural': 'Company Events'},
        ),
    ]
