# Generated by Django 5.2 on 2025-05-17 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_alter_aboutcompany_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutcompany',
            options={'ordering': ['year'], 'verbose_name': 'Company Event', 'verbose_name_plural': 'Company Events'},
        ),
    ]
