# Generated by Django 5.2 on 2025-05-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_vacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(blank=True, verbose_name='Ответ'),
        ),
    ]
